server:
  port: ${PORT:0}

#Database configs
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123huehuebrfdp
  h2: 
    console:
      enabled: true
      path: /h2-console